colors_2ODD_functions:
    "AOP2" : "#4e7b3a"
    "AOP3" : "#4a7638"
    "DPS" : "#4a7637"
    "GA20ox" : "#6aa84f"
    "C20-GA2ox": "#93c47d"
    "C19-GA2ox": "#b6d7a8"
    "GA2ox" : "#759c63"
    "DAO" : "#9bb78f"
    "GA3ox" : "#b6d7a8"
    "GA13ox" : "#a0bd94"
    "GA7ox" : "#e8eed0"
    "2ODDC23" : "#fff2cc"
    "LFS" : "#f4e8c3"
    "2OG1" : "#ffe599"
    "C2'H" : "#ffd966"
    "F6'H" : "#dbc7b0"
    "S8H" : "#ffc466"
    "GSLOH" : "#e6bd5a"
    "GRS" : "#c8b478"
    "TIIAS" : "#c1b9a0"
    "D4H" : "#bb9e9e"
    "BX6" : "#e0bbbb"
    "FNSI" : "#f4cccc"
    "FNSI_F3H" : "#d6b3b3"
    "FNSI_FLS" : "#dcb8b8"
    "F3H" : "#f4cccc"
    "FLS_F3H" : ""
    "H6H" : "#e9d0db"
    "IDS" : "#e9d0db"
    "SLC" : "#cfe2f3"
    "GIM" : "#d0d2e5"
    "M2H" : "#c27ba0"
    "M2H_weak" : "#e1afbc"
    "DMR6" : "#c2d3e2"
    "S5H" : "#abbbc9"
    "S3H" : "#95a3af"
    "FLS" : "#b4a7d6"
    "LDOX" : "#8e7cc3"
    "JOX" : "#6fa8dc"
    "ACCO" : "#3d85c6"
    "T6OD" : "#3371a8"
    "COD" : "#316ca2"
    "SRG" : "#316a9f"
    "LBO" : "#2c6190"

