import pytest

#from bio_tools.homology.paralog import return_paralogous_leaves


TEST_TREE_NEWICK_STR = """
(   
    (
        (
            (
                (
                    (
                        (
                            F1_E:0.7
                        ):0.45,
                        (
                            (
                                F1_D:0.5
                            ):0.45,
                            (
                                (
                                    F1_C:0.6
                                ):0.7,
                                (
                                    F1_B:0.9,
                                    F1_A:0.7
                                ):0.3
                            ):0.3
                        ):0.3
                    ):0.8,
                    (
                        (
                            F2_E
                        ):0.145,
                        (
                            (
                                F2.1_C
                            ):0.145,
                            (
                                (
                                    F2.2_C
                                ):0.17,
                                (
                                    F2_B:0.09,
                                    F2_A:0.07
                                ):0.13
                            ):0.09
                        ):0.09
                    ):0.08
                ):0.4,
                (
                    F3_A:0.05,
                    F3_C:0.06
                ):0.4
            ):0.4
        ):0.4,
        (
            (
                (
                    F4_E:0.7
                ):0.45,
                (
                    (
                        F4_D:0.5
                    ):0.45,
                    (
                        (
                            F4.1_C:0.04,
                            F4.2_C:0.05
                        ):0.03,
                        (
                            F4_B:0.9,
                            F4_A:0.7
                        ):0.3
                    ):0.3
                ):0.3
            ):0.4,
            (
                (
                    (
                        (                
                            (
                                (
                                    F5.1_A:0.04,
                                    F5.1_B:0.05
                                ):0.3,
                                (
                                    F5.2_A:0.04,
                                    F5.2_B:0.05
                                ):0.3
                            ):0.3,
                            (
                                (
                                    F5.3_B 
                                ):0.2
                            ):0.23 
                        ):0.3,
                        (
                            F5_D:0.9 
                        ):0.2
                    ):0.4
                )
            ):0.35
        ):0.3
    ):0.3, 
    (
        (
            (
                (
                    (
                        F6_A
                    ):0.3, 
                    (
                        (
                            (
                                F6_B
                            ):0.3, 
                            (
                                (
                                    F6.1_C:2.0
                                ):0.92,
                                (
                                    (
                                        (
                                            F6.2_C
                                        ):0.09, 
                                        (
                                            (
                                                (
                                                    F6.3_C:0.02
                                                )0.02,
                                                (
                                                    F6.4_C:0.03
                                                )0.03
                                            )
                                        ):0.2
                                    ):0.4
                                )   
                            ):0.2
                        ):0.3
                    )   
                ):0.2 
            )
        ):0.3, 
        (
            (
                (
                    (
                        (
                            (
                                F7_A:0.3
                            )0.3,
                            (
                                F7.1_B:0.4
                            )0.2
                        ):0.2,
                        (
                            (
                                F7_C:0.4,
                                F7.2_B:0.4
                            ):0.3, 
                            (
                                F7_D:0.4
                            ):0.3
                        ):0.3
                    ):0.3
                ):0.3
            )0:3
        )
    )
);
"""


# todo: test PATH to newick file
# todo: test BioPhylo tree? 
# todo: test dendropy tree
# todo: test 
"""
@pytest.mark.parametrize(
        "input, expected", 
        [
            (
                TEST_TREE_NEWICK_STR, 

            )
        ]
)
def test_return_paralogous_leaves(input, expected):
"""


